### PR TITLE
First drafts additional Style-guide-rules

### PR DESCRIPTION
**Pull request by SanderElias**
WIP

### CODE REVIEW

**Review by tomwhite007 — COMMENTED** [review]
Nice discussion points. Happy to reach consensus on all of those.

However, Nx is considered required reading for enterprise applications in the UK (and I presume most places) - as with all the other Extended Ecosystem items listed. This study plan is currently designed to look at the wider ecosystem - so that it adds value for professional developers who want to achieve a pay grade. I'm not saying the demo code repo needs to include all that, but the guide is intended to do so.

This is just my opinion. So please push back if you disagree :)

**Review by tomwhite007 — COMMENTED** [review]
Thanks for the update. It's much clearer to me now - and negates some of my last comment.

If I may, I'll quote and comment on three points:

> inputs and outputs should be limited to max 5.

Do you mean 5 in total, or 5 inputs and 5 outputs?
(I'm happy to agree to either, but recommend '5 in total' for simple demos)

>3rd party libs
>  * should not be used at all if possible!

Abolutely agreed, but with one caveat:
Unless the 3rd party lib _is_ the study topic - e.g. Storybook

> * for experts the same, but perhaps with NX/lerna? ~~Although I do have some doubts about this. (let me explain, those things are actually tooling that has little to nothing to do with Angular, although they are related)~~ 

I'd be happy to not use Nx at all - unless Nx or Published Libraries _is_ the topic

As with all my comments, these are only my opinions and I'm happy to defer to you if you feel strongly.

**Comment by SanderElias** [comment]
@tomwhite007 I did address, a few comments of you in the text. Added a few things too.
And yes, of course, if the 3rth party is the subject of the lesson, it's allowed. (we need to be careful not to put in too many of those tho. 
But that's an additional reason to have lazy-loaded demos. it keeps the 3rth party inside the lesson and doesn't bleed into the "general population"

I think we should ban all CSS frameworks tho. (again, except when it _is_ the lesson.), But we do need to provide some basic global styling. 
Hmm, let me add that to the doc.

**Review by tomwhite007 — APPROVED** [review]
Love it. Thanks Sander.
@Stephenradams are you happy?

**Comment by Stephenradams** [comment]
Yes @tomwhite007 I think this looks great. @SanderElias  if you want to merge this in I'm happy

**Comment by SanderElias** [comment]
@Stephenradams, @tomwhite007 
image

Would love to merge it, but I seem to have hit some stage bug there....

**Comment by Stephenradams** [comment]
@SanderElias  that was odd, I've been able to merge it. @tomwhite007 is this an issue with the repo or shall we leave it like this so only you and I can merge?

**Comment by tomwhite007** [comment]
I've added Sander as Write access. I had assumed Bonnie had invited him
already.

When we migrate to Angular Nation GitHub group, Sander will have full
access.

**Pull request merged**
